BROKER_DEFAULT="IDIRECT"
BROKER_IDIRECT="IDIRECT"
BROKER_KITE="KITE"
BROKER_UPSTOX="UPSTOX"
BROKER_TEST="TEST"
DATAPROVIDER_DEFAULT="IDIRECT"
DATAPROVIDER_IDIRECT="IDIRECT"

API_KEY=""
SECRET_KEY=""
LOGIN_URL="https://api.icicidirect.com/apiuser/login?api_key="
SESSION_TOKEN_NAME="apisession"

IDIRECT_API_KEY=""
IDIRECT_SECRET_KEY=""
IDIRECT_LOGIN_URL="https://api.icicidirect.com/apiuser/login?api_key="
IDIRECT_SESSION_TOKEN_NAME="apisession"

KITE_API_KEY=""
KITE_SECRET_KEY=""
KITE_LOGIN_URL="https://kite.zerodha.com/connect/login?v=3&api_key="
KITE_SESSION_TOKEN_NAME="kite.request_token"

UPSTOX_API_KEY=""
UPSTOX_SECRET_KEY=""
UPSTOX_LOGIN_URL="https://api.upstox.com/v2/login/authorization/dialog?response_type=code&redirect_uri=http://[2406:da1a:11ba:bb00:311d:3e2:5194:8745]:5000/authorize&state=myTradingAppstate&client_id="
UPSTOX_SESSION_TOKEN_NAME="code"
UPSTOX_LOGOUT_URL="https://api.upstox.com/v2/logout"
UPSTOX_REDIRECT_URL="http://[2406:da1a:11ba:bb00:311d:3e2:5194:8745]:5000/authorize"
